services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkreader:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: . # uncomment to build from source
    # image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - ${PORT:-3031}:3000
    labels:
      - "homepage.group=Bookmarks"
      - "homepage.name=Linkreader"
      - "homepage.icon=linkwarden.png"
      - "homepage.href=http://localhost:${PORT:-3031}"
      - "homepage.description=Self-hosted read-it-later app"
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
